---
- name: Download OpenSearch archive to localhost
  ansible.builtin.get_url:
    url: "{{ os_download_url }}/{{ os_version }}/opensearch-{{ os_version }}-linux-x64.tar.gz"
    dest: /tmp/opensearch.tar.gz
    mode: "644"
  become: false
  delegate_to: localhost
  run_once: true

- name: Create OpenSearch user
  ansible.builtin.user:
    name: "{{ os_user }}"
    state: present
    shell: /bin/false
    create_home: true
    home: "{{ os_home }}"

- name: Create OpenSearch home directory
  ansible.builtin.file:
    path: "{{ os_home }}"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: "755"

- name: Upload OpenSearch and extract
  ansible.builtin.unarchive:
    src: /tmp/opensearch.tar.gz
    dest: "{{ os_home }}"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    extra_opts: ["--strip-components=1", "--show-stored-names"]

- name: Copy configuration file
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.template', 'opensearch_' ~ cluster_type ~ '.yml.j2') }}"
    dest: "{{ os_config_dir }}/opensearch.yml"
    state: present
    create: true
    marker: "## {mark} OpenSearch main configuration ##"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: "600"

- name: Copy jvm.options file for instance
  ansible.builtin.template:
    src: jvm.options.j2
    dest: "{{ os_config_dir }}/jvm.options"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: "600"
    force: true

- name: Create OpenSearch systemd service
  ansible.builtin.template:
    src: opensearch.service.j2
    dest: /etc/systemd/system/opensearch.service
    mode: "644"
