---
- name: Pre-setup
  ansible.builtin.import_playbook: playbook_pre_setup.yml

- name: Setup Ceph ADM
  ansible.builtin.import_playbook: playbook_setup_adm.yml

- name: Setup Ceph common
  ansible.builtin.import_playbook: playbook_setup_common.yml
  when: not is_single_node

- name: Apply Ceph OSDs
  ansible.builtin.import_playbook: playbook_apply_osd.yml

- name: Apply Ceph OSDs
  ansible.builtin.import_playbook: playbook_openstack_init.yml
