---
- name: Deploy and setup Filebeat
  hosts: controller, compute, storage
  become: true
  vars_files:
    - "{{ root_dir ~ '/inventories/' ~ target_env ~ '/nodes.yml' }}"
  roles:
    - role: filebeat
