---
- name: Initialize database
  ansible.builtin.include_role:
    name: common
    tasks_from: init_database
  vars:
    db_name: keystone
    db_user: keystone
    db_password: "{{ keystone_password }}"

- name: Install Keystone package
  ansible.builtin.package:
    name: keystone
    state: present

- name: Setup configuration
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Populate the identity service database
  ansible.builtin.command:
    cmd: sudo -u keystone keystone-manage db_sync
  changed_when: false

- name: Initialize Fernet key repositories
  ansible.builtin.shell:
    cmd: |
      sudo -u keystone keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
      sudo -u keystone keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
    executable: /bin/bash
  changed_when: false

- name: Bootstrap the identity service
  ansible.builtin.shell:
    cmd: |
      sudo -u keystone keystone-manage bootstrap --bootstrap-password {{ os_keystone_password }} \
      --bootstrap-admin-url http://{{ controller01_host_addr }}:5000/v3/ \
      --bootstrap-internal-url http://{{ controller01_host_addr }}:5000/v3/ \
      --bootstrap-public-url http://{{ controller01_host_addr }}:5000/v3/ \
      --bootstrap-region-id RegionOne
    executable: /bin/bash
  changed_when: false

- name: Reconfigure Apache2 configuration - add ServerName
  ansible.builtin.blockinfile:
    path: /etc/apache2/apache2.conf
    append_newline: true
    prepend_newline: true
    block: ServerName {{ controller01_host_addr }}
    insertafter: EOF

- name: Start and enable Apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: true

- name: Create a domain, projects, users, and roles
  ansible.builtin.include_tasks:
    file: create_identity.yml
