---
ansible_connection: ssh
ansible_ssh_common_args: -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no -o "PubkeyAuthentication=no"

ntp_server: time.aws.com

ceph_pub_key_fetch_path: /tmp/fetch-ceph.pub
device_name: vdb

ceph_common_nodes: "{{ groups.ceph_common | default([]) }}"
is_single_node: "{{ ceph_common_nodes | length == 0 }}"

mon_count: "{{ is_single_node | ternary(1, 3) }}"
mgr_count: "{{ is_single_node | ternary(1, 2) }}"
