---
- name: Print architecture variables
  ansible.builtin.debug:
    msg: |
      Architecture: {{ ansible_facts['architecture'] }}
      OS: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} ({{ ansible_facts['distribution_release'] }})

- name: Install required packages
  ansible.builtin.package:
    pkg:
      - ca-certificates
      - curl
  any_errors_fatal: true

- name: Add Docker engine repository
  block:
    - name: Check if the OS distribution is Ubuntu
      ansible.builtin.fail:
        msg: The OS distribution is not Ubuntu, go to rescue block
      when: '"Ubuntu" not in ansible_facts["distribution"]'

    - name: Create directory for Docker's GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "755"

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present
      register: add_docker_gpg_key
      until: add_docker_gpg_key.key_id is defined and add_docker_gpg_key.short_id is defined
      retries: 10

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ arch_mapping[ansible_facts['architecture']] | default(ansible_facts['architecture']) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb'].codename }} stable
        filename: docker
        state: present

    - name: Remove any other packages which are potentially conflicting
      ansible.builtin.package:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent
  rescue:
    - name: Rescued
      ansible.builtin.debug:
        msg: The OS distribution is RHEL

    - name: Add Docker repository
      ansible.builtin.yum_repository:
        name: docker-ce
        baseurl: https://download.docker.com/linux/centos/{{ ansible_facts['distribution_major_version'] }}/x86_64/stable/
        description: Docker CE repository
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Remove any other packages which are potentially conflicting
      ansible.builtin.package:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
          - podman
          - runc
        state: absent

- name: Install Docker and related packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  any_errors_fatal: true

- name: Add Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password: "{{ ansible_password | password_hash('sha512', 'mysecretsalt') }}"
    groups: docker
    append: true

- name: Configure http proxy
  ansible.builtin.include_tasks:
    file: configure_http_proxy.yml
