---
ansible_user: vagrant
ansible_password: vagrant
ansible_sudo_pass: vagrant

os_sys_user: opensearch
os_sys_dashboards_user: opensearch-dashboards

os_admin_user: admin
os_admin_password: admin12345

os_kibana_user: kibana
os_kibana_password: kibana12345

os_dashboards_admin_user: admin
os_dashboards_admin_password: admin12345
