---
ansible_user: vagrant
ansible_password: vagrant
ansible_sudo_pass: vagrant

os_user: opensearch
os_dashboards_user: opensearch-dashboards

os_dashboards_admin_user: admin
os_dashboards_admin_password: admin12345
