---
ansible_connection: ssh
ansible_ssh_common_args: -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no -o "PubkeyAuthentication=no"

os_cluster_name: openstack-cluster
os_download_url: https://artifacts.opensearch.org/releases/bundle/opensearch
os_version: 3.4.0
os_api_port: 9200
os_home: /usr/share/opensearch
os_config_dir: /usr/share/opensearch/config

xms_value: 2
xmx_value: 2

cluster_type: single-node

os_dashboards_version: 3.4.0
os_dashboards_home: /usr/share/opensearch-dashboards
os_dashboards_config_dir: /usr/share/opensearch-dashboards/config

logstash_download_url: https://artifacts.elastic.co/downloads/logstash
logstash_version: 9.2.3
logstash_beat_port: 5044
logstash_home: /usr/share/logstash

filebeat_download_url: https://artifacts.elastic.co/downloads/beats/filebeat
filebeat_version: 9.2.3
filebeat_home: /usr/share/filebeat
