---
ansible_user: vagrant
ansible_password: vagrant
ansible_sudo_pass: vagrant

rabbitmq_password: vagrant
os_keystone_password: vagrant
os_placement_password: vagrant
os_nova_password: vagrant
os_neutron_password: vagrant
cinder_password: vagrant
os_cinder_password: vagrant
metadata_secret: vagrant
os_octavia_password: vagrant
